### ISSUE TITLE
Tests: Make report only show differences in parsed code

### ISSUE THREAD

**Issue by mvnmgrx** [mvnmgrx/kiutils#25]
The HTML test report shows the expected and produced output for each test. It would be nice to see only the differences between those two, as it is not easy to pinpoint where the issue is looking at the report itself. Maybe some kind of github-like diff or something ..

**Comment by aphera** [comment]
Hi @mvnmgrx I have a 8 line change set that accomplishes this enhancement. Would love to create a PR and get your thoughts on it.

**Comment by mvnmgrx** [comment]
Hello @aphera, sounds great! Looking forward for your PR on this topic.

**Comment by aphera** [comment]
https://github.com/mvnmgrx/kiutils/pull/42

**Comment by mvnmgrx** [comment]
Added in #42
