### ISSUE TITLE
Python 3.10 required

### ISSUE THREAD

**Issue by MatteoTondelli** [mvnmgrx/kiutils#6]
I tried to use your library with **Python 3.6.1** and since union types written as `X | Y` is a **Python 3.10** feature ([PEP604](https://peps.python.org/pep-0604/)), I can't use it with my old Python version.

I don't think this is a _real issue_, my suggestion is to simply add in the prerequisite something like `Python version 3.10 or greater` or thinking to handle this with older Python versions.

**Comment by mvnmgrx** [comment]
Yes, this library was written with Python 3.10 in mind as i really like the idea of type annotations in the code to hint at the data being stored in all those objects.

I've added a prerequisites section to the docu to show what Python version is needed. Thanks for letting me know!
