### ISSUE TITLE
Footprint Attribute "Exempt from courtyard requirement" is not parsed

### ISSUE THREAD

**Issue by chfriedrich** [mvnmgrx/kiutils#99]
Hi,
the relatively new Footprint Attribute "Exempt from courtyard requirement" is not parsed by the lib right now.
If I set it with kicad and manipulate the footprint lib with kiutils afterwards, the attribute will be removed.

Best regards,
Christoph

**Comment by mvnmgrx** [comment]
Thanks for the info. This will work in the next release.

Best regards
